# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59626a9e626581528c27b5303516a0bdbb95174dc3315efefa967f13088c9e7fdfd36d8e9770b38da496733b9f44eff8ad1cea1cbf19c6c00f3d8651ce4c8522

test:
  secret_key_base: e0c02089f6606d7b2cd5d56a79dc1f31e88427db04e576fa9ac45048ff642c4a0e7fb7e841d00036fe3603515338c2977732ea8c91ad0b7c565cc5ffc0af8fe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
